In [1]:
def collatz(n):
    pasos=0
    if n >= 2:
        while n != 1:
            if n%2==0:
                pasos=pasos+1
                n = n/2
            else:
                pasos=pasos+1
                n=3*n+1
    return pasos
collatz(3)

7

In [15]:
def diamond(rows):
    total_diamond=""
    mid_row=rows/2-0.5
    if rows%2==0:
        raise ValueError("Poner un número impar")
    for i in range(rows):
        if i <= mid_row:
            nelemen=1+i*2
        else:
            row_factor=2*(i-mid_row)
            nelemen=rows-row_factor
            
        row=("*"*int(nelemen)).center(rows," ")
        total_diamond+=row + "\n"
        print(row)
diamond(3)

 * 
***
 * 


In [17]:
from math import sqrt
import pdb
def distancia(V,W):
    dist=0
    for v, w in zip(V,W):
        dist+=(v-w)**2
        
    return sqrt(dist)

In [11]:
times1= lambda x, y:x * y
(lambda x, y:x * y)(2,3)

6

In [12]:
(lambda x, y: x ** y)(2,2)

4

In [43]:

list(map(lambda x: x ** 2, range(1,11)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [46]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [78]:
func = [lambda x: x+x, lambda x: x-x, lambda x:x*x, lambda x:x/x]

[[2, 0, 1, 1.0],
 [4, 0, 4, 1.0],
 [6, 0, 9, 1.0],
 [8, 0, 16, 1.0],
 [10, 0, 25, 1.0],
 [12, 0, 36, 1.0],
 [14, 0, 49, 1.0],
 [16, 0, 64, 1.0],
 [18, 0, 81, 1.0]]

In [89]:
list(map(lambda f: list(map(f,range(1,11))), func))

[[2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100],
 [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]

In [92]:
elementos=[1,2,3,4,5,6,7,8,9]
list(filter(lambda x: x%2 != 0, elementos))

[1, 3, 5, 7, 9]

In [121]:
materias = ["CALCULO","FINANZAS","OPTIMIZACION","GEOMETRIA","PROGRAMACION","ESTADISTICA"]
list(map(lambda x: x.lower(), materias))

['calculo',
 'finanzas',
 'optimizacion',
 'geometria',
 'programacion',
 'estadistica']

In [131]:
materias = ["CALCULO","FINANZAS","OPTIMIZACION","GEOMETRIA","PROGRAMACION","ESTADISTICA"]
list(filter(lambda x: len(x) > 10, materias))

['OPTIMIZACION', 'PROGRAMACION', 'ESTADISTICA']

In [132]:
list(map(lambda x: x.lower(), filter(lambda x: len(x)>10, materias)))

['optimizacion', 'programacion', 'estadistica']

In [139]:
list(filter(lambda x: x%2!=0, map(lambda x: x**2, range(1,12))))

[1, 9, 25, 49, 81, 121]

In [143]:
[x**2 for x in range(1,12)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

In [142]:
[x**2 for x in range(1,12) if x % 2 == 1]

[1, 9, 25, 49, 81]

In [144]:
p = {1:2,2:3,4:7,7:17}
print(p[p[4]])

17


In [146]:
sum([x for x in range(1000) if x%5 == 0 or x%3 == 0])

233168

In [153]:
conjunto_potencia_unidades = lambda n, lim: {x: list({x**p % 10 for p in range(1,lim+1)}) for x in range(n+1)}

In [154]:
conjunto_potencia_unidades(10,20)

{0: [0],
 1: [1],
 2: [8, 2, 4, 6],
 3: [9, 3, 1, 7],
 4: [4, 6],
 5: [5],
 6: [6],
 7: [9, 3, 1, 7],
 8: [8, 2, 4, 6],
 9: [9, 1],
 10: [0]}

In [6]:
U=[1,3,3,10]
def F(x): return x > 10
def G(x): return x%2==1
any(F(x) for x in U if G(x))

False

In [17]:
A=[0,2,4,6]
B=[0,1,2,3]
def F(a,b): return a==b*2


all([any([F(a, b) for a in A]) for b in B])

True

In [25]:
U = [36,33,43,75,21,92,16,34,31,35,80,45,47,10,52,45,21,58,30,42]
def implies(a,b): return not(a and not b)
def par(x): return x%2 == 0
def impar(x): return not par(x)


all(implies(par(x), not impar(x))for x in U)

True

In [26]:
any([par(x) and impar(x) for x in U])

False

In [41]:
U = [range(1999,3001)]
X = [(2010,"Feb"),(2010,"Jan"),(2011,"Feb"),(2015,"Dec"),(2018,"Feb"),(2018,"Aug")]
Y = ["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
def F(x): return 2010 <= x <= 2018
[F(x[0]) and not (x[0] == 2018 and x[1] in Y) for x in X]

[True, True, True, True, True, False]

In [3]:
import numpy
arr1=numpy.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1.ndim

2

In [5]:
arr1.shape

(2, 3)

In [11]:
import numpy as np
np.array([1,2])

1

In [13]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [14]:
arr1.sum(1)

array([ 6, 15])

In [21]:
A = [[1,2,3],[4,5,6]]
[any([ai < 3 for ai in a]) for a in A]

[True, False]

In [22]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [32]:
i=np.arange(0,100)
i*(i+100)

array([    0,   101,   204,   309,   416,   525,   636,   749,   864,
         981,  1100,  1221,  1344,  1469,  1596,  1725,  1856,  1989,
        2124,  2261,  2400,  2541,  2684,  2829,  2976,  3125,  3276,
        3429,  3584,  3741,  3900,  4061,  4224,  4389,  4556,  4725,
        4896,  5069,  5244,  5421,  5600,  5781,  5964,  6149,  6336,
        6525,  6716,  6909,  7104,  7301,  7500,  7701,  7904,  8109,
        8316,  8525,  8736,  8949,  9164,  9381,  9600,  9821, 10044,
       10269, 10496, 10725, 10956, 11189, 11424, 11661, 11900, 12141,
       12384, 12629, 12876, 13125, 13376, 13629, 13884, 14141, 14400,
       14661, 14924, 15189, 15456, 15725, 15996, 16269, 16544, 16821,
       17100, 17381, 17664, 17949, 18236, 18525, 18816, 19109, 19404,
       19701])

In [155]:
arr = np.arange(25).reshape(5, 5); arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Recordar: arr[COLUMNAS, FILAS]

In [109]:
arr[2:-1,2:-1]

array([[12, 13],
       [17, 18]])

In [111]:
arr[1:]=0
arr

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [156]:
arr[[0,-1]] = arr[0]+100,arr[-1]+200
arr

array([[100, 101, 102, 103, 104],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [220, 221, 222, 223, 224]])

In [158]:
x=10
y=10
[[x*y for x in range(1,x+1)]for y in range(1,y+1)]

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
 [6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
 [7, 14, 21, 28, 35, 42, 49, 56, 63, 70],
 [8, 16, 24, 32, 40, 48, 56, 64, 72, 80],
 [9, 18, 27, 36, 45, 54, 63, 72, 81, 90],
 [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]

In [178]:
def pyramid(v):
    vlen = len(str(v))
    max_len = v * 4
    for i in range(v + 1):
        label = format(i, f"0{vlen}")
        print((f"{label} " * i).center(max_len))
    
pyramid(10)

                                        
                  01                    
                 02 02                  
               03 03 03                 
              04 04 04 04               
            05 05 05 05 05              
           06 06 06 06 06 06            
         07 07 07 07 07 07 07           
        08 08 08 08 08 08 08 08         
      09 09 09 09 09 09 09 09 09        
     10 10 10 10 10 10 10 10 10 10      


In [5]:
FV = 100
C = 5
r = 0.05
n = 20
PV = FV/((1+r)**n) + sum([C/((1+r)**i) for i in range(1,1+n)])

In [6]:
PV

99.99999999999996

In [8]:
FV = 100
C = 5
r = 0.05
n = 20

PV = FV/((1+r)**n) + sum([(FV*0.1*(1+r)**i)/((1+r)**i) for i in range(1,n+1)])
PV

237.68894828730004

In [21]:
class Estudiante:
    def __init__(self, nombre, ap_paterno, ap_materno, edad, licenciatura):
        self.nombre = nombre
        self.ap_paterno = ap_paterno
        self.ap_materno = ap_materno
        self.edad = edad
        self.licenciatura = licenciatura
        self.__calificaciones = {}
        
    def agregar_materias(self, materia):
        self.materia = __calificaciones[materia][10]

In [22]:
Victor = ("Víctor", "Michel", "Juárez", 19, "Actuaría")

In [24]:
Victor.agregar_materias()

AttributeError: 'tuple' object has no attribute 'agregar_materias'